WebApplication/Areas/QLBHXH/Controllers/DanhSachDieuChinhChucDanhController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRM.QLBHXH.Models;
using System.Web.Script.Serialization;
using System.Globalization;


namespace HRM.QLBHXH.Controllers
{
    public class DanhSachDieuChinhChucDanhController : Controller
    {
        private HRMDB1Entities db = new HRMDB1Entities();
        private HRM.Databases.Models.HRMDBEntities db1 = new Databases.Models.HRMDBEntities();
    //    private HRM.Databases.Models.dmChucDanh db1 = new HRM.Databases.Models.dmChucDanh();
        //
        // GET: /DanhSachDieuChinhChucDanh/

        public ActionResult Index()
        {
            var nvbhdanhsachdieuchinhchucdanhs = db.nvbhDanhSachDieuChinhChucDanh.Include(n => n.dmLoaiDieuChinh).Include(n => n.nvbhNhanVienBHXH);
            return View(nvbhdanhsachdieuchinhchucdanhs.ToList());
        }


        //su dung index2 de ap dung jquery slide
        public ActionResult Index2(string BD = "")
        {
            int maxId = (from c in db.nvbhDanhSachDieuChinhTangGiam select c.MoiNhat).Max();
            ViewBag.idmoi = maxId;
            
            var nvbhdanhsachdieuchinhchucdanhs = from ds in db.v_ChucDanh select ds;
            int NgayHT = DateTime.Now.Day;
            int ThangHT = DateTime.Now.Month;
            int NamHT = DateTime.Now.Year;
            int thang = ThangHT;
            string DotCuaThang = ""; 



            int thang1 = 1;
            int nam1 = 1;
            string ngaybd1 = "01/01/2014";
            string ngaykt1 = "01/01/2014";

            if (BD != "")
            {

                //int thanght=1, namht=1;
                thang1 = int.Parse(BD.Substring(0, 2));
                nam1 = int.Parse(BD.Substring(3, 4));
                DotCuaThang = thang1.ToString("D2") + "/" + nam1;
            }
            else
            {

                if (BD == "")
                {
                    thang1 = ThangHT;
                    nam1 = NamHT;
                    DotCuaThang = ThangHT.ToString("D2") + "/" + NamHT;
                }
            }
            switch (thang1)
            {
                case 1: ngaybd1 = "12/21/" + (nam1 - 1); ngaykt1 = "01/20/" + nam1; break;
                case 2: ngaybd1 = "01/21/" + nam1; ngaykt1 = "02/20/" + nam1; break;
                case 3: ngaybd1 = "02/21/" + nam1; ngaykt1 = "03/20/" + nam1; break;
                case 4: ngaybd1 = "03/21/" + nam1; ngaykt1 = "04/20/" + nam1; break;
                case 5: ngaybd1 = "04/21/" + nam1; ngaykt1 = "05/20/" + nam1; break;
                case 6: ngaybd1 = "05/21/" + nam1; ngaykt1 = "06/20/" + nam1; break;
                case 7: ngaybd1 = "06/21/" + (nam1); ngaykt1 = "07/20/" + nam1; break;
                case 8: ngaybd1 = "07/21/" + nam1; ngaykt1 = "08/20/" + nam1; break;
                case 9: ngaybd1 = "08/21/" + nam1; ngaykt1 = "09/20/" + nam1; break;
                case 10: ngaybd1 = "09/21/" + nam1; ngaykt1 = "10/20/" + nam1; break;
                case 11: ngaybd1 = "10/21/" + nam1; ngaykt1 = "11/20/" + nam1; break;
                case 12: ngaybd1 = "11/21/" + nam1; ngaykt1 = "12/20/" + (nam1 + 1); break;
            }

            DateTime start = DateTime.ParseExact(ngaybd1, "MM/dd/yyyy", CultureInfo.CurrentCulture);
            DateTime end = DateTime.ParseExact(ngaykt1, "MM/dd/yyyy", CultureInfo.CurrentCulture);
            ViewBag.NgayBD = ngaybd1;

            ViewBag.NgayKT = ngaykt1;
            TempData["startdate"] = ngaybd1;
            TempData["enddate"] = ngaykt1;

            nvbhdanhsachdieuchinhchucdanhs = from ds in db.v_ChucDanh where ds.idLoaiDieuChinh == 9 && start <= ds.TuThangNam && ds.TuThangNam <= end select ds;

            ViewBag.Dot = DotCuaThang;
            //var count = from ds in db.v_nvbhDanhSachDieuChinhTangGiam where start <= ds.NgayPhatSinh && ds.NgayPhatSinh <= end && ds.XacNhan == false select ds;
            //TempData["count"] = count.Count();
            return View(nvbhdanhsachdieuchinhchucdanhs.ToList());
        }

        //
        // GET: /DanhSachDieuChinhChucDanh/Details/5

        public ActionResult Details(int id = 0)
        {
            nvbhDanhSachDieuChinhChucDanh nvbhdanhsachdieuchinhchucdanh = db.nvbhDanhSachDieuChinhChucDanh.Find(id);
            if (nvbhdanhsachdieuchinhchucdanh == null)
            {
                return HttpNotFound();
            }
            return View(nvbhdanhsachdieuchinhchucdanh);
        }

        //
        // GET: /DanhSachDieuChinhChucDanh/Create

        public PartialViewResult Create()
        {



            ViewBag.idLoaiDieuChinh = new SelectList(db.dmLoaiDieuChinh, "id", "LoaiDieuChinh");
            HRM.Databases.Models.dmChucDanh cd1 = new Databases.Models.dmChucDanh();
        
          var dv = db.nvbhNhanVienBHXH.Select(m => new { m.Donvi_id, m.DonVi }).Distinct().ToList();
          ViewBag.dsdonvi = new SelectList(dv, "Donvi_id", "DonVi");
            ViewBag.idnvbhNhanVienBHXH = new SelectList(db.nvbhNhanVienBHXH, "NV_id", "HoVaTen");
            //DateTime ngayht = DateTime.Now.Date;
            //ViewBag.ngayht = ngayht;
            return PartialView();
        }


        //danh sach nhan vien de su dung khi chon dv se xuat hien ten nv
        public string nvds(int dvid)
        {
                return new JavaScriptSerializer().Serialize(
                                from y in db.nvbhNhanVienBHXH
                                where y.Donvi_id==dvid

                                select new { value = y.NV_id, key = y.HoVaTen });
        }


        //
        // POST: /DanhSachDieuChinhChucDanh/Create

        [HttpPost]
        public ActionResult Create(nvbhDanhSachDieuChinhTangGiam nvbhdanhsachdieuchinhchucdanh)
        {
            if (ModelState.IsValid)
            {
                db.nvbhDanhSachDieuChinhTangGiam.Add(nvbhdanhsachdieuchinhchucdanh);
                db.SaveChanges();
                TempData["Message"] = "Thêm thành công";
                return RedirectToAction("Index2");
            }
            else
            {
                TempData["Message"] = "Thêm không thành công";
                return RedirectToAction("Index2");
            }

            return View(nvbhdanhsachdieuchinhchucdanh);
        }

        //
        // GET: /DanhSachDieuChinhChucDanh/Edit/5

        public ActionResult Edit(int id = 0)
        {
            nvbhDanhSachDieuChinhChucDanh nvbhdanhsachdieuchinhchucdanh = db.nvbhDanhSachDieuChinhChucDanh.Find(id);
            if (nvbhdanhsachdieuchinhchucdanh == null)
            {
                return HttpNotFound();
            }
            ViewBag.idLoaiDieuChinh = new SelectList(db.dmLoaiDieuChinh, "id", "LoaiDieuChinh", nvbhdanhsachdieuchinhchucdanh.idLoaiDieuChinh);
            ViewBag.idnvbhNhanVienBHXH = new SelectList(db.nvbhNhanVienBHXH, "id", "HoVaTen", nvbhdanhsachdieuchinhchucdanh.idnvbhNhanVienBHXH);
            return View(nvbhdanhsachdieuchinhchucdanh);
        }

        //
        // POST: /DanhSachDieuChinhChucDanh/Edit/5

        [HttpPost]
        public ActionResult Edit(nvbhDanhSachDieuChinhChucDanh nvbhdanhsachdieuchinhchucdanh)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nvbhdanhsachdieuchinhchucdanh).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idLoaiDieuChinh = new SelectList(db.dmLoaiDieuChinh, "id", "LoaiDieuChinh", nvbhdanhsachdieuchinhchucdanh.idLoaiDieuChinh);
            ViewBag.idnvbhNhanVienBHXH = new SelectList(db.nvbhNhanVienBHXH, "id", "HoVaTen", nvbhdanhsachdieuchinhchucdanh.idnvbhNhanVienBHXH);
            return View(nvbhdanhsachdieuchinhchucdanh);
        }

        //
        // GET: /DanhSachDieuChinhChucDanh/Delete/5

        public PartialViewResult Delete(int id = 0)
        {
            nvbhDanhSachDieuChinhTangGiam nvbhdanhsachdieuchinhtanggiam = db.nvbhDanhSachDieuChinhTangGiam.Find(id);

            ViewBag.hovaten = from nv in db.nvbhNhanVienBHXH where nv.NV_id == nvbhdanhsachdieuchinhtanggiam.NV_id select nv.HoVaTen;
            ViewBag.manv = from nv in db.nvbhNhanVienBHXH where nv.NV_id == nvbhdanhsachdieuchinhtanggiam.NV_id select nv.MANV;
            ViewBag.sobh = from nv in db.nvbhNhanVienBHXH where nv.NV_id == nvbhdanhsachdieuchinhtanggiam.NV_id select nv.SoBHXH;
           
            
            //if (nvbhdanhsachdieuchinhchucdanh == null)
            //{
            //    return HttpNotFound();
            //}
            return PartialView(nvbhdanhsachdieuchinhtanggiam);
        }


        // GET: /Qua Trinh

        public PartialViewResult QuaTrinh(int id = 0)
        {
            nvbhDanhSachDieuChinhTangGiam nvbhdanhsachdieuchinhtanggiam = db.nvbhDanhSachDieuChinhTangGiam.Find(id);
            ViewBag.Manv = from nv in db.nvbhNhanVienBHXH where nv.NV_id == nvbhdanhsachdieuchinhtanggiam.NV_id select nv.MANV;
            ViewBag.tennv = from nv in db.nvbhNhanVienBHXH where nv.NV_id == nvbhdanhsachdieuchinhtanggiam.NV_id select nv.HoVaTen;
            return PartialView(nvbhdanhsachdieuchinhtanggiam);
        }

        //
        // POST: /Qua Trinh

        [HttpPost]
        public ActionResult QuaTrinh(nvbhDanhSachDieuChinhTangGiam nvbhdanhsachdieuchinhtanggiam)
        {
            if (ModelState.IsValid)
            {
                nvbhdanhsachdieuchinhtanggiam.XacNhan = true;
                db.Entry(nvbhdanhsachdieuchinhtanggiam).State = EntityState.Modified;
                db.SaveChanges();


                TempData["Message"] = "Đưa vào quá trình thành công";
            }
            return RedirectToAction("Index2");
        }

        //
        // POST: /DanhSachDieuChinhChucDanh/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {

WebApplication/Areas/QLBHXH/Views/DanhSachDieuChinhChucDanh/Create.cshtml
@model HRM.QLBHXH.Models.nvbhDanhSachDieuChinhTangGiam
@{
    ViewBag.Title = "Create";
    
}
<h2>
    Tạo mới điều chỉnh chức danh</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>nvbhDanhSachDieuChinhChucDanh</legend>
        @Html.HiddenFor(model => model.idLoaiDieuChinh, new { @Value = 9 })
        Tên đơn vị(<font color="red"><b>*</b></font>):
        <div class="editor-label">@Html.DropDownList("dsdonvi", "--Chọn đơn vị--")
        </div>
        Tên nhân viên(<font color="red"><b>*</b></font>):
        <div class="editor-field">
            @Html.DropDownList("idnvbhNhanVienBHXH", "--Chọn Tên nhân viên--")
            @Html.HiddenFor(model => model.idnvbhNhanVienBHXH, new { @id = "idnv" })
        </div>
        @Html.HiddenFor(model => model.Tang, new { Value = "Thay đổi chức danh công việc, nghề, điều kiện, nơi làm việc" })
        @Html.HiddenFor(model => model.NV_id)
        @Html.HiddenFor(model => model.DonVi_id)
        <div class="editor-field">
            @Html.HiddenFor(model => model.NgayPhatSinh, new { @value = DateTime.Now.ToLongDateString() })
            @Html.ValidationMessageFor(model => model.NgayPhatSinh)
        </div>
        <div class="editor-label">
            Chức vụ cũ
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.CVCu)
            @Html.ValidationMessageFor(model => model.CVMoi)
        </div>
        <div class="editor-label">
            Chức vụ mới(<font color="red"><b>*</b></font>):
        </div>
        <div class="editor-field">
            @Html.DropDownList("ChucVu", "--Chọn chức vụ--")
            @Html.HiddenFor(model => model.CVMoi)
            @Html.ValidationMessageFor(model => model.CVMoi)
        </div>
        <div class="editor-label">
            Từ tháng năm(<font color="red"><b>*</b></font>):
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.TuThangNam)
            @Html.ValidationMessageFor(model => model.TuThangNam)
        </div>
        <div class="editor-label">
            Đến tháng năm
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DenThangNam)
            @Html.ValidationMessageFor(model => model.DenThangNam)
        </div>
        <div class="editor-label">
            Ghi chú
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.GhiChu)
            @Html.ValidationMessageFor(model => model.GhiChu)
        </div>
        <font color="red"><b>(*)Không được để trống</b></font>
        <p>
            <input type="submit" value="Tạo" onclick="return check();" />
        </p>
    </fieldset>
}
<script>
//script cho datetime picker
    $("#NgayPhatSinh").datepicker({
        changeDay: true,
       changeMonth: true,
        changeYear: true,
    });
      $("#TuThangNam").datepicker({
        changeDay: true,
       changeMonth: true,
        changeYear: true,
    });
      $("#DenThangNam").datepicker({
        changeDay: true,
       changeMonth: true,
        changeYear: true,
    });

    //combobox
    var dv = $("[id$=dsdonvi]").combobox();
    var ten = $("[id$=idnvbhNhanVienBHXH").combobox();
   var CV= $("[id$=ChucVu]").combobox();
    

    //cascade combobox
    dv.change(function () {
        ten.trigger("connect", "/hrm/QLBHXH/DanhSachDieuChinhChucDanh/nvds?dvid=" + $(this).val());
         var text1 = $(this).val();
        $("[id$=DonVi_id]").val(text1);
    });
    ten.change(function () {
        var text = $(this).val();
        $("[id$=NV_id]").val(text);
    });
        CV.change(function () {
        var text1 =$("#ChucVu option:selected").text();
        $("[id$= CVMoi]").val(text1);
    });
   
     
    //thong bao loi neu cac truong bi null
    function check() {
        if (document.getElementById('dsdonvi').value == "") {
            alert("Tên đơn vị không được bỏ trống!");
            return false;
        }
        if (document.getElementById('idnvbhNhanVienBHXH').value == "") {
            alert("Tên nhân viên không được bỏ trống!");
            return false;
        }
           if (document.getElementById('CVMoi').value == "") {
            alert("Tên chức vụ mới không được bỏ trống!");
            return false;
        }
            if (document.getElementById('TuThangNam').value == "") {
            alert("Từ tháng năm không được bỏ trống!");
            return false;
        }


    }
    //css cho combobox
     $(".custom-combobox-input").removeClass("ui-state-default");
    $(".custom-combobox-input").removeClass("ui-widget-content");
    $(".custom-combobox-input").removeClass("ui-corner-left");
    $(".custom-combobox-toggle").removeClass("ui-state-default");
</script>

WebApplication/Areas/QLBHXH/Views/DanhSachDieuChinhChucDanh/Delete.cshtml
@using HRM.Webpages.Helpers
@model HRM.QLBHXH.Models.nvbhDanhSachDieuChinhTangGiam

@{
    ViewBag.Title = "Delete";
    var hoten = ViewBag.hovaten;
}
<h3>Bạn có muốn xóa thông tin?</h3>

<fieldset>
    <legend>nvbhDanhSachDieuChinhTangGiam</legend>         
        @Html.VN("Loại điều chỉnh: ")
        <b>@Html.DisplayFor(model => model.dmLoaiDieuChinh.LoaiDieuChinh)</b>
        <br />

    @*    @Html.VN("Loại: ")
        <b>@Html.DisplayFor(model => model.dmLoaiTangGiam.LoaiTangGiam)</b>
        <br />*@

        @Html.VN("Họ và tên: ")
   

           <b>  @Html.Display("hovaten", String.Empty)  </b> 
        <br />

        @Html.VN("Mã nhân viên: ")
        <b>        @Html.Display("manv", String.Empty)</b>
        <br />

        @Html.VN("Số sổ BHXH: ")
        <b>        @Html.Display("sobh", String.Empty)</b>
        <br />

        @Html.VN("Ngày phát sinh: ")
        <b>@Html.DisplayFor(model => model.NgayPhatSinh)</b>



    
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Xóa" />      
    </p>
}

WebApplication/Areas/QLBHXH/Views/DanhSachDieuChinhChucDanh/Details.cshtml
@model HRM.QLBHXH.Models.nvbhDanhSachDieuChinhChucDanh

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>nvbhDanhSachDieuChinhChucDanh</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.dmLoaiDieuChinh.LoaiDieuChinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.dmLoaiDieuChinh.LoaiDieuChinh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.nvbhNhanVienBHXH.HoVaTen)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.nvbhNhanVienBHXH.HoVaTen)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.NgayPhatSinh)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.NgayPhatSinh)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChucVuCu)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChucVuCu)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ChucVuMoi)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ChucVuMoi)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.TuThangNam)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.TuThangNam)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DenThangNam)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DenThangNam)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.GhiChu)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.GhiChu)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication/Areas/QLBHXH/Views/DanhSachDieuChinhChucDanh/Index2.cshtml
@model IEnumerable<HRM.QLBHXH.Models.v_ChucDanh>
@using HRM.Webpages.Helpers
@{
    ViewBag.Title = "Index";
    string ngayBD = ViewBag.NgayBD;
    string ngayKT = ViewBag.NgayKT;
    string Dot = ViewBag.Dot;
    int idmoi = ViewBag.idmoi;
    //int Thang = ViewBag.Thang;
}
@Html.StatusMessage(TempData["Message"])

 <div>
             <a style="text-align: right" title="Trở lại danh sách NV BHXH" onclick="location.href='@Url.Action("index2", "NhanVienBHXH")'"><span class="ui-icon     
ui-icon-arrowreturnthick-1-w " style="display: inline-block" /></a>
    Đợt của tháng:<input  name="From" title="Từ ngày" id="txt1" value=@Dot  />  <input type="button" value="Lọc" id="Loc" /> 
@*     <input type="button" value="Xác nhận" id="qt" />*@
  <input type="button" value="Thêm điều chỉnh chức danh" id="btncreate" />
    </div>
<div id="create"></div>
<div id="delete"></div>
<table id="dieuchinhCD">
    <thead>
        <tr>
              <th style="text-align: center" nowrap>
               Mới nhất
            </th>
            <th style="text-align:center" nowrap>
                Họ và tên
            </th>
           @* <th style="text-align:center" nowrap>
               Ngày phát sinh
            </th>*@
            <th style="text-align:center" nowrap>
                Chức vụ cũ
            </th>
            <th style="text-align:center" nowrap>
               Chức vụ mới
            </th>
            <th style="text-align:center" nowrap>
              Từ tháng năm
            </th>
            <th style="text-align:center" nowrap>
            Đến tháng năm
            </th>
            <th style="text-align:center" nowrap>
              Ghi chú
            </th>
            <th style="text-align:center" nowrap>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
              <td style="text-align: left" nowrap>
                    @Html.DisplayFor(modelItem => item.MoiNhat)
                </td>
                <td style="text-align:center" nowrap>
                    @Html.DisplayFor(modelItem => item.HoVaTen)
                </td>
 
                <td style="text-align:center" nowrap>
                   
                </td>
                <td style="text-align:center" nowrap>
                    @Html.DisplayFor(modelItem => item.CVMoi)
                </td>
                     <td style="text-align: left" nowrap>
                 @item.TuThangNam.ToString("MM/yyyy")
  
                </td>
        
                <td style="text-align:center" nowrap>
                    
                </td>
                <td style="text-align:center" nowrap>
                    @Html.DisplayFor(modelItem => item.GhiChu)
                </td>
                <td style="text-align:center" nowrap>
                   <a data-val1="@item.id" title="Xóa" class='btnxoa'><span class="ui-icon ui-icon-trash"
                        style="display: inline-block" /></a>

                </td>
            </tr>
        }
    </tbody>
</table>

@*nguon cua fix cac cot trong bang*@
<script src="~/Scripts/datatables/FixedColumns.js"></script>
<script>

    // Script cho bảng
    $(document).ready(function () {
        var oTable = $('#dieuchinhCD').dataTable({
            "bJQueryUI": true,
            "sScrollY": "100%",
            "sScrollX": "100%"
            ,
       "bSort": false,
        "aoColumns": [{"bVisible": false },null,null,null,null,null,null,null ]
                      ,
            "fnRowCallback": function (nRow, aData, iDisplayIndex) {

                if (aData[0] == @idmoi) {
                    $(nRow).css('background-color', '#FFFFCC');
                      $(nRow).css(  'border', '1px solid #999');
                }
            }
        });
        
        new /*$.fn.dataTable.*/FixedColumns(oTable, {
            "iLeftColumns": 1,
            "iRightColumns": 1
        })
    });


    //hide nut dong tat ca cac the div
    $(".button2").hide();
    //lay create view cho vao the div create
    $.get("../DanhSachDieuChinhChucDanh/Create").success(function (data) {
        $('#create').html(data);
    });
//     $.get("../DanhSachDieuChinhChucDanh/delete").success(function (data) {
//                $('#delete').html(data);
//                    });
    //chuyen div create thanh tab
    $("#create").tabs();
        $("#delete").tabs();

    //ban nut create div create truot xuong
    $("#btncreate").click(function () {
        $("#create").slideToggle("medium");
   
  
    });


      $(function () {
        $('.btnxoa').click(function () {
            var Val1 = $(this).attr("data-val1");
            //goi delete view len tab
            $.get("../DanhSachDieuChinhChucDanh/delete?id=" + Val1).success(function (data) {
                $('#delete').html(data);
        $("#delete").slideToggle("medium");
            });
          

     

        });
    });

       


  
    //ban nut create div create truot xuong
//    $("#btnxoa").click(function () {
//        $("#delete").slideToggle("medium");

//    });

       //xu li nut filter
          $("#Loc").click(function () {
           var txtVal = $("#txt1").val();
    
            window.location = "@Url.Action("Index2", "DanhSachDieuChinhChucDanh")" +"?BD=" + txtVal;
        }); 



        
    //datetime picker


  $("#txt1").datepicker( {
        changeMonth: true,
        changeYear: true,
        showButtonPanel: true
        ,
        dateFormat: 'MM yy',
      
                 onClose: function(dateText, inst) {
      var month = $("#ui-datepicker-div .ui-datepicker-month :selected").val();
      var year = $("#ui-datepicker-div .ui-datepicker-year :selected").val();
      $(this).val($.datepicker.formatDate('mm/yy', new Date(year, month, 1)));
 
    }

});

$("#txt1").focus(function () {
  $(".ui-datepicker-calendar").hide();
  $("#ui-datepicker-div").position({
    my: "center top",
    at: "center bottom",
    of: $(this)
  });
});

//$("#txt1").datepicker('disable');
//  $("#txt1").ui-datepicker-calendar {
//    display: none;
//    };
     


</script>
  <style type="text/css">
    #create, #delete
    {
        display: none;
    }

        input#txt1
    {
        width: 100px;
    }
           input#txt2
    {
        width: 100px;
    }
   
</style>